export const OFFICIAL_AUDIO_FORMAT_OPTIONS = [
  ["wav32", "WAV 32-bit float"],
  ["wav", "WAV"],
  ["flac", "FLAC"],
  ["mp3", "MP3"],
  ["opus", "Opus"],
  ["aac", "AAC"],
] as const;

export const OFFICIAL_AUDIO_FORMAT_VALUES = OFFICIAL_AUDIO_FORMAT_OPTIONS.map(([value]) => value);

export const ACE_STEP_KEY_SCALE_OPTIONS = [
  "auto",
  "A major",
  "A minor",
  "A# major",
  "A# minor",
  "Ab major",
  "Ab minor",
  "A♯ major",
  "A♯ minor",
  "A♭ major",
  "A♭ minor",
  "B major",
  "B minor",
  "B# major",
  "B# minor",
  "Bb major",
  "Bb minor",
  "B♯ major",
  "B♯ minor",
  "B♭ major",
  "B♭ minor",
  "C major",
  "C minor",
  "C# major",
  "C# minor",
  "Cb major",
  "Cb minor",
  "C♯ major",
  "C♯ minor",
  "C♭ major",
  "C♭ minor",
  "D major",
  "D minor",
  "D# major",
  "D# minor",
  "Db major",
  "Db minor",
  "D♯ major",
  "D♯ minor",
  "D♭ major",
  "D♭ minor",
  "E major",
  "E minor",
  "E# major",
  "E# minor",
  "Eb major",
  "Eb minor",
  "E♯ major",
  "E♯ minor",
  "E♭ major",
  "E♭ minor",
  "F major",
  "F minor",
  "F# major",
  "F# minor",
  "Fb major",
  "Fb minor",
  "F♯ major",
  "F♯ minor",
  "F♭ major",
  "F♭ minor",
  "G major",
  "G minor",
  "G# major",
  "G# minor",
  "Gb major",
  "Gb minor",
  "G♯ major",
  "G♯ minor",
  "G♭ major",
  "G♭ minor",
] as const;

export const ACE_STEP_TIME_SIGNATURE_OPTIONS = [
  ["", "Auto"],
  ["2", "2/4"],
  ["3", "3/4"],
  ["4", "4/4"],
  ["6", "6/8"],
] as const;

export const ACE_STEP_ADVANCED_PAYLOAD_FIELDS = [
  "infer_method",
  "sampler_mode",
  "use_adg",
  "cfg_interval_start",
  "cfg_interval_end",
  "timesteps",
  "dcw_enabled",
  "dcw_mode",
  "dcw_scaler",
  "dcw_high_scaler",
  "dcw_wavelet",
  "retake_seed",
  "retake_variance",
  "enable_normalization",
  "normalization_db",
  "fade_in_duration",
  "fade_out_duration",
  "latent_shift",
  "latent_rescale",
  "mp3_bitrate",
  "mp3_sample_rate",
  "auto_score",
  "auto_lrc",
  "return_audio_codes",
  "save_to_library",
  "use_tiled_decode",
  "is_format_caption",
  "device",
  "dtype",
  "use_flash_attention",
  "compile_model",
  "offload_to_cpu",
  "offload_dit_to_cpu",
  "vae_checkpoint",
  "reference_audio",
  "src_audio",
  "audio_codes",
  "global_caption",
  "instruction",
  "audio_cover_strength",
  "cover_noise_strength",
  "repainting_start",
  "repainting_end",
  "chunk_mask_mode",
  "repaint_mode",
  "repaint_strength",
  "repaint_latent_crossfade_frames",
  "repaint_wav_crossfade_sec",
  "flow_edit_morph",
  "flow_edit_source_caption",
  "flow_edit_source_lyrics",
  "flow_edit_n_min",
  "flow_edit_n_max",
  "flow_edit_n_avg",
  "track_name",
  "track_classes",
] as const;

export type AceStepAdvancedField = (typeof ACE_STEP_ADVANCED_PAYLOAD_FIELDS)[number];

export type AceStepAdvancedValues = Partial<Record<AceStepAdvancedField, unknown>> & {
  audio_format?: string;
  batch_size?: number;
  inference_steps?: number;
  guidance_scale?: number;
  shift?: number;
  seed?: number;
};

export const ACE_STEP_ADVANCED_DEFAULTS: Partial<Record<AceStepAdvancedField, unknown>> = {
  infer_method: "ode",
  sampler_mode: "euler",
  use_adg: false,
  cfg_interval_start: 0,
  cfg_interval_end: 1,
  timesteps: "",
  dcw_enabled: true,
  dcw_mode: "double",
  dcw_scaler: 0.05,
  dcw_high_scaler: 0.02,
  dcw_wavelet: "haar",
  retake_seed: "",
  retake_variance: 0,
  enable_normalization: true,
  normalization_db: -1,
  fade_in_duration: 0,
  fade_out_duration: 0,
  latent_shift: 0,
  latent_rescale: 1,
  mp3_bitrate: "128k",
  mp3_sample_rate: 48000,
  auto_score: false,
  auto_lrc: false,
  return_audio_codes: false,
  save_to_library: false,
  use_tiled_decode: true,
  is_format_caption: false,
  device: "auto",
  dtype: "auto",
  use_flash_attention: "auto",
  compile_model: false,
  offload_to_cpu: false,
  offload_dit_to_cpu: false,
  vae_checkpoint: "official",
  global_caption: "",
  instruction: "",
  audio_cover_strength: 1,
  cover_noise_strength: 0,
  repainting_start: 0,
  repainting_end: -1,
  chunk_mask_mode: "auto",
  repaint_mode: "balanced",
  repaint_strength: 0.5,
  repaint_latent_crossfade_frames: 10,
  repaint_wav_crossfade_sec: 0,
  flow_edit_morph: false,
  flow_edit_source_caption: "",
  flow_edit_source_lyrics: "",
  flow_edit_n_min: 0,
  flow_edit_n_max: 1,
  flow_edit_n_avg: 1,
  track_name: "",
  track_classes: [],
};
