export const ACE_STEP_LANGUAGE_OPTIONS = [
  ["unknown", "Auto / unknown"],
  ["ar", "Arabic"],
  ["az", "Azerbaijani"],
  ["bg", "Bulgarian"],
  ["bn", "Bengali"],
  ["ca", "Catalan"],
  ["cs", "Czech"],
  ["da", "Danish"],
  ["de", "German"],
  ["el", "Greek"],
  ["en", "English"],
  ["es", "Spanish"],
  ["fa", "Persian"],
  ["fi", "Finnish"],
  ["fr", "French"],
  ["he", "Hebrew"],
  ["hi", "Hindi"],
  ["hr", "Croatian"],
  ["ht", "Haitian Creole"],
  ["hu", "Hungarian"],
  ["id", "Indonesian"],
  ["is", "Icelandic"],
  ["it", "Italian"],
  ["ja", "Japanese"],
  ["ko", "Korean"],
  ["la", "Latin"],
  ["lt", "Lithuanian"],
  ["ms", "Malay"],
  ["ne", "Nepali"],
  ["nl", "Dutch"],
  ["no", "Norwegian"],
  ["pa", "Punjabi"],
  ["pl", "Polish"],
  ["pt", "Portuguese"],
  ["ro", "Romanian"],
  ["ru", "Russian"],
  ["sa", "Sanskrit"],
  ["sk", "Slovak"],
  ["sr", "Serbian"],
  ["sv", "Swedish"],
  ["sw", "Swahili"],
  ["ta", "Tamil"],
  ["te", "Telugu"],
  ["th", "Thai"],
  ["tl", "Tagalog"],
  ["tr", "Turkish"],
  ["uk", "Ukrainian"],
  ["ur", "Urdu"],
  ["vi", "Vietnamese"],
  ["yue", "Cantonese"],
  ["zh", "Chinese"],
] as const;

export const ACE_STEP_LANGUAGE_CODES = ACE_STEP_LANGUAGE_OPTIONS.map(([code]) => code);

